### ISSUE TITLE
リロード時に一番上だったら読み込んだとき一番上に飛ばしてほしい

### ISSUE THREAD

**Issue by takax3** [Dragon-Egg/sleeping_syar#28]
## 概要
すくろーるめどい
できれば設定からチェックボックスでON/OFFできるといいな

**Comment by Crow314** [comment]
現状の仕様ではタブ名をタップすると最上部に移動します。
スクロールが面倒なのは百歩譲ってわかるとして、タブ名タップの動作くらい必要経費と割り切って下さい。
