### ISSUE TITLE
スクロール中に最上段に飛んだ際の処理が変

### ISSUE THREAD

**Issue by takax3** [Dragon-Egg/sleeping_syar#30]
## 不具合概要
下に向かってスクロールして速度が残ってる状態でタブタップで最上段に飛んだとき、飛んでからスクロールしちゃう

## 該当ページ
タイムラインとか

## 再現手順
1. 勢いよくスクロールする
2. タブ名をタップして上に戻る

## 本来の挙動
止まってほしい

## 修正しないとどう困るか
なんか気持ち悪い

## 原因
速度が残ってる

**Comment by shin19** [comment]
修正

**Comment by takax3** [comment]
THX!!!!
